/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cheroliv.util

import java.io.File
import mu.KotlinLogging
import kotlin.text.Charsets.UTF_8

private val log = KotlinLogging.logger {}

class App {

    companion object {
        const val FILTER_FILENAME: String = "result.txt"
        const val RESULT_FILENAME: String = "node_modules_file_paths.txt"
        const val MOTIF_FILENAME: String = "node_modules"
    }

    val greeting: String
        get() {
            return "Hello world."
        }

    fun builder(path: String, motif: String) {
        val pathsFile = File(path)
        val pathsSequence = pathsFile.readText(UTF_8).lineSequence()
       // for ((index, value) in pathsSequence.withIndex()) {
            //println("The element at $index is $value")
        //}

    }
}

fun main() {
    val app = App()
    println(app.greeting)
    app.builder(App.RESULT_FILENAME, App.MOTIF_FILENAME)
}
